/* STORE ALL CONSTANTS HERE */

/* HTTP STATUS CODES */
export const HTTP_BAD_REQUEST = 400; // Generic client error status code
export const HTTP_OK = 200; // Successful HTTP request
export const HTTP_CREATED = 201; // Resource created successfully
export const HTTP_NOT_FOUND = 404; // Resource not found
export const HTTP_SERVER_ERROR = 500; // Generic server error status code
export const HTTP_UNAUTHORIZED = 401; // Unauthorized access
export const HTTP_FORBIDDEN = 403; // Forbidden access
export const HTTP_NO_CONTENT = 204; // Successful request with no content
export const HTTP_CONFLICT = 409; // Conflict with current state of the resource
export const HTTP_UNPROCESSABLE_ENTITY = 422; // Unprocessable entity
export const HTTP_TOO_MANY_REQUESTS = 429; // Too many requests
export const HTTP_RESET_CONTENT = 205; // Reset content
export const HTTP_PARTIAL_CONTENT = 206; // Partial content
export const HTTP_ACCEPTED = 202; // Request accepted for processing
export const HTTP_NOT_MODIFIED = 304; // Not modified
export const HTTP_MOVED_PERMANENTLY = 301; // Moved permanently
export const HTTP_FOUND = 302; // Found (Previously "Moved temporarily")
export const HTTP_SEE_OTHER = 303; // See other resource
export const HTTP_TEMPORARY_REDIRECT = 307; // Temporary redirect
export const HTTP_NOT_ACCEPTABLE = 406; // Not acceptable
export const HTTP_PROXY_AUTHENTICATION_REQUIRED = 407; // Proxy authentication required
export const HTTP_REQUEST_TIMEOUT = 408; // Request timeout
export const HTTP_LENGTH_REQUIRED = 411; // Length required
export const HTTP_PRECONDITION_FAILED = 412; // Precondition failed
export const HTTP_PAYLOAD_TOO_LARGE = 413; // Payload too large
export const HTTP_URI_TOO_LONG = 414; // URI too long
export const HTTP_UNSUPPORTED_MEDIA_TYPE = 415; // Unsupported media type
export const HTTP_RANGE_NOT_SATISFIABLE = 416; // Range not satisfiable
export const HTTP_EXPECTATION_FAILED = 417;  // Expectation failed
export const HTTP_MISDIRECTED_REQUEST = 421; // Misdirected request
export const HTTP_UNAVAILABLE_FOR_LEGAL_REASONS = 451; // Unavailable for legal reasons
export const HTTP_GONE = 410; // Gone
export const HTTP_REQUEST_HEADER_FIELDS_TOO_LARGE = 431; // Request header fields too large
export const HTTP_BAD_GATEWAY = 502; // Bad gateway
export const HTTP_SERVICE_UNAVAILABLE = 503; // Service unavailable
export const HTTP_GATEWAY_TIMEOUT = 504; // Gateway timeout
export const HTTP_VERSION_NOT_SUPPORTED = 505; // HTTP version not supported
export const HTTP_VARIANT_ALSO_NEGOTIATES = 506; // Variant also negotiates
export const HTTP_INSUFFICIENT_STORAGE = 507; // Insufficient storage
export const HTTP_LOOP_DETECTED = 508; // Loop detected
export const HTTP_NOT_EXTENDED = 510;    // Not extended
export const HTTP_NETWORK_AUTHENTICATION_REQUIRED = 511; // Network authentication required


/* Response Messages */
export const SUCCESS_MSG = 'success';
export const ERROR_MSG = 'error';
export const NOT_FOUND_MSG = 'Resource not found';
export const SERVER_ERROR_MSG = 'Internal server error';
export const UNAUTHORIZED_MSG = 'Unauthorized access';
export const FORBIDDEN_MSG = 'Forbidden access';
export const VALIDATION_ERROR_MSG = 'Validation error';
export const CONFLICT_MSG = 'Conflict with current state of the resource';
export const TOO_MANY_REQUESTS_MSG = 'Too many requests';
export const SERVICE_UNAVAILABLE_MSG = 'Service unavailable';
export const BAD_REQUEST_MSG = 'Bad request';
export const CREATED_MSG = 'Resource created successfully';
export const UPDATED_MSG = 'Resource updated successfully';
export const DELETED_MSG = 'Resource deleted successfully';
export const NO_CONTENT_MSG = 'No content';
export const PARTIAL_CONTENT_MSG = 'Partial content delivered';
export const ACCEPTED_MSG = 'Request accepted for processing';
export const NOT_MODIFIED_MSG = 'Resource not modified';
export const REDIRECT_MSG = 'Resource moved temporarily';
export const LENGTH_REQUIRED_MSG = 'Content length required';
export const PRECONDITION_FAILED_MSG = 'Precondition failed';
export const PAYLOAD_TOO_LARGE_MSG = 'Payload too large';
export const URI_TOO_LONG_MSG = 'URI too long';
export const UNSUPPORTED_MEDIA_TYPE_MSG = 'Unsupported media type';
export const RANGE_NOT_SATISFIABLE_MSG = 'Range not satisfiable';
export const EXPECTATION_FAILED_MSG = 'Expectation failed';
export const MISDIRECTED_REQUEST_MSG = 'Misdirected request';
export const UNAVAILABLE_FOR_LEGAL_REASONS_MSG = 'Unavailable for legal reasons';
export const GONE_MSG = 'Resource gone';
export const REQUEST_HEADER_FIELDS_TOO_LARGE_MSG = 'Request header fields too large';
export const BAD_GATEWAY_MSG = 'Bad gateway';
export const GATEWAY_TIMEOUT_MSG = 'Gateway timeout';
export const VERSION_NOT_SUPPORTED_MSG = 'HTTP version not supported';
export const INSUFFICIENT_STORAGE_MSG = 'Insufficient storage';
export const LOOP_DETECTED_MSG = 'Loop detected';
export const NOT_EXTENDED_MSG = 'Not extended';
export const NETWORK_AUTHENTICATION_REQUIRED_MSG = 'Network authentication required';
